language: generic
before_deploy:
- sudo add-apt-repository ppa:koffeinflummi/armake -y
- sudo apt-get update -y
- sudo apt-get install armake -y
- "./deploy.sh"
deploy:
  skip_cleanup: true
  provider: releases
  file_glob: true
  file: release/*.zip
  on:
    repo: 7Cav/SandboxAndTrainingMissionGenerator
    tags: true
  api_key:
    secure: IquymHODdICiNlSlpJLwrj6dZXS7J4WK5rIuTvUUQX2qF6ZhgHWNkovlr4cWNFY0+nZrCgwfcbXLhtVpId7CxrIWCXUpzoSUojUatpk0NhWIrRSiGT76oZf6p134vZcLfISGBNfq4bG4QewT20wvJbBH8ObXmfYSUW1yd+2Rn7Msm5R/i98YRO3YFsQCWgDUJJJmfdHy0zHhxuK0GW5G9g9I4evCn1eWo4A8GDQXKhpD4vvnfyW7TDucd6ofRhvTAIwJlGthfeq6msZLxVJ8LZ1L13onEeErOPV8iGfe37r2SbXTNdlBuvs2PwM2QtrO+NbzFK5Wzozc5D7mldZbvVZDkzneHSnXQG2FGFt7h3c/TFOcc/GDALlpwcrp0GqdqzbCfh7uCo0oB5WXEvTFwbpZnR7WwOhv6Fmn52/wBOIvzIhVEnvLwmsUaoS/SnV29gGRZ7Ct0HGKEAQW1KfxB7dQ5dw8dWFZJm5zyRcfTpYnck9yzXyThaSlFX64D+SunsKyZeytz1/Umuu7AkV6stxgNz/DoGzsNQyxSWoOZozGyu6/tqdFL03o7BoCBT1K76QTFStsWeZMyW7dhSZyltcfpsGsAwkm4GiPbS55TO6FW+1ean59ushaRQzvfXPN71aoRFVTz0W0+gqC+uyqyAFCl0xilHxFmKmPTo+4SdE=