language: python
python:
- '3.5'
install:
- sudo add-apt-repository ppa:koffeinflummi/armake -y
- sudo apt-get update -y
- sudo apt-get install armake -y
- pip3 install --upgrade pip
script: make test
before_deploy:
- deploy.sh
deploy:
  skip_cleanup: true
  provider: releases
  file_glob: true
  file: release/*.zip
  on:
    repo: 7Cav/SandboxAndTrainingMissionGenerator
    tags: true
  api-key:
    secure: Y40YjBvS/PkGr5N+toJUOyCb+O4LgrvSsjNLkWJOWESPA7joqU/MZMuR7cnMHjd+CL+j52Z6XTFllgZaKfW5c3faEVDlr74+aM5HC6iLjo2l7GWc7U+LkgnhLPgEgDeTLLNVtq56aecL9KNRZ1oqCCmA605yY4ZizdXCI3JPSFU7wazkqkaD7malNLQdi6nImcYy/SvCZo3HvaUpXvz5TF9lXz6o9+slTfD4aOoYqoQl7ofHDHDeoluR1cfUTEaAsMu0AhSd99dQOu7FA+O/wBP6+BTiLa5BoKWd3g4ogO1V27cyoTEIslLXHz7WX+2a9e9AZBrXpjvtvQ+SeCs1fYmzPswZieN08ykWD4B5gtTvrM0tlK6N6gBuYmMR1S3ATq08Lr8w1CEUL68cBW2FARuUbBv0k0hpSAkhoYgRVuthk2d04j0YsatFSgYlzPxm2bwj/HqOn/vpRl/BOn3ZdwFSaO214sKT9TDkkAgZiRdJ3tTtGaDDcNyCkHIklrQBscaiAv787dsGyejiZpjaoFTJ3qvM5dUKF6tnayVGTjb5t60ShkJaFR/FwtjZO1m5kFAlmAA5u5w/qXlAM9Wx4/BwaWP06Z4thFF/kWi/BVJ8xbIoYT/XH0jO/MLvbU4YHvgd3jpxWk4hnyfQmNGVXBIf68i7/+54kNpqamyRFpY=
