name: Testing
on: [push, pull_request]
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Checking json format
        if: always()
        run: bash scripts/checkFormat.sh