name: Testing
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, ready_for_review]

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Checking json format
        if: always()
        run: bash scripts/checkFormat.sh