name: Testing
on: [push, pull_request]
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
    - name: Checking json format
      if: always()
      run: bash scripts/checkFormat.sh
      continue-on-error: true